/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.motorph.payroll.view;

import com.motorph.payroll.GUI;
import com.motorph.payroll.controller.AttendanceController;
import com.motorph.payroll.controller.EmployeeController;
import com.motorph.payroll.controller.PayrollController;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Window;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
/**
 *
 * @author Arvee
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    private PayrollView view;
    private EmployeeController employeeController;
    private AttendanceController attendanceController;
    private PayrollController payrollController;
    
    public MainMenu() {
        initComponents();
    }
    
    public MainMenu(PayrollView view, EmployeeController employeeController,
            AttendanceController attendanceController, PayrollController payrollController) {
        this.view = view;
        this.employeeController = employeeController;
        this.attendanceController = attendanceController;
        this.payrollController = payrollController;
        
        initComponents();
        
        // to make the window center on the screen.
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
        btnLogout.setVisible(false); // For Now Set to False for MS2
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnEmployeeList = new javax.swing.JButton();
        btnRecords = new javax.swing.JButton();
        btnManageAttendance = new javax.swing.JButton();
        btnGenerate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblLogo2 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 0, 51));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(165, 154, 202));
        jPanel1.setMaximumSize(new java.awt.Dimension(805, 538));
        jPanel1.setMinimumSize(new java.awt.Dimension(805, 538));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEmployeeList.setBackground(new java.awt.Color(204, 204, 204));
        btnEmployeeList.setFont(new java.awt.Font("FZYaoTi", 1, 18)); // NOI18N
        btnEmployeeList.setForeground(new java.awt.Color(0, 0, 0));
        btnEmployeeList.setText("View Employee List");
        btnEmployeeList.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEmployeeList.setOpaque(true);
        btnEmployeeList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeListActionPerformed(evt);
            }
        });
        jPanel2.add(btnEmployeeList, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 190, 30));

        btnRecords.setBackground(new java.awt.Color(204, 204, 204));
        btnRecords.setFont(new java.awt.Font("FZYaoTi", 2, 10)); // NOI18N
        btnRecords.setForeground(new java.awt.Color(0, 0, 0));
        btnRecords.setText("View Attendance Records");
        btnRecords.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecordsActionPerformed(evt);
            }
        });
        jPanel2.add(btnRecords, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 190, 30));

        btnManageAttendance.setBackground(new java.awt.Color(204, 204, 204));
        btnManageAttendance.setFont(new java.awt.Font("FZYaoTi", 2, 10)); // NOI18N
        btnManageAttendance.setForeground(new java.awt.Color(0, 0, 0));
        btnManageAttendance.setText("Manage Attendance");
        btnManageAttendance.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAttendanceActionPerformed(evt);
            }
        });
        jPanel2.add(btnManageAttendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 190, 30));

        btnGenerate.setBackground(new java.awt.Color(204, 204, 204));
        btnGenerate.setFont(new java.awt.Font("FZYaoTi", 2, 10)); // NOI18N
        btnGenerate.setForeground(new java.awt.Color(0, 0, 0));
        btnGenerate.setText("Generate Payslip");
        btnGenerate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });
        jPanel2.add(btnGenerate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 190, 30));

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DASHBOARD");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 55));

        lblLogo2.setBackground(new java.awt.Color(0, 0, 0));
        lblLogo2.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 26)); // NOI18N
        lblLogo2.setForeground(new java.awt.Color(255, 255, 255));
        lblLogo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo2.setText("MotorPH");
        lblLogo2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblLogo2.setOpaque(true);
        jPanel2.add(lblLogo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 140, 50));

        btnLogout.setBackground(new java.awt.Color(174, 0, 1));
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("LOGOUT");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, 20));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLabel3.setOpaque(true);
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 230, 250));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/motorphbackground.jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -210, 880, 740));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-65, -32, 880, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        for (Window window : Window.getWindows()) {
            if (window instanceof JFrame) {
                window.dispose(); // Closes all JFrame windows
            }
        }
        new GUI().setVisible(false); // For Now Set to False for MS2
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        new GeneratePayslipId(view, employeeController).setVisible(true);
    }//GEN-LAST:event_btnGenerateActionPerformed

    private void btnManageAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAttendanceActionPerformed
        new AttendanceId(employeeController, attendanceController).setVisible(true);
    }//GEN-LAST:event_btnManageAttendanceActionPerformed

    private void btnRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordsActionPerformed
        new RecordsEmpId(view, employeeController, attendanceController, payrollController).setVisible(true);
    }//GEN-LAST:event_btnRecordsActionPerformed

    private void btnEmployeeListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeListActionPerformed
        new EmployeeList(employeeController).setVisible(true);
    }//GEN-LAST:event_btnEmployeeListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmployeeList;
    private javax.swing.JButton btnGenerate;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageAttendance;
    private javax.swing.JButton btnRecords;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblLogo2;
    // End of variables declaration//GEN-END:variables
}
