/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.motorph.payroll.view;

import com.motorph.payroll.controller.AttendanceController;
import com.motorph.payroll.controller.PayrollController;
import com.motorph.payroll.model.Employee;
import com.motorph.payroll.model.PayrollSummary;
import java.awt.Dimension;
import java.awt.Toolkit;
/**
 *
 * @author Arvee
 */
public class RecordsChoices extends javax.swing.JFrame {

    private PayrollView view;
    private Employee employee;
    private PayrollSummary payrollSummaryAll;
    private AttendanceController attendanceController;
    private PayrollController payrollController;
    /**
     * Creates new form RecordsChoices
     */
    public RecordsChoices() {
        initComponents();
    }
    
    public RecordsChoices(PayrollView view, Employee employee, PayrollSummary payrollSummaryAll,
            AttendanceController attendanceController, PayrollController payrollController) {
        initComponents();
        
        // to make the window center on the screen.
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
        
        this.view = view;
        this.employee = employee;
        this.payrollSummaryAll = payrollSummaryAll;
        this.attendanceController = attendanceController;
        this.payrollController = payrollController;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        allRecordsBtn = new javax.swing.JButton();
        specificPeriodBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        allRecordsBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        allRecordsBtn.setText("View All Attendance Records");
        allRecordsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allRecordsBtnActionPerformed(evt);
            }
        });

        specificPeriodBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        specificPeriodBtn.setText("View Attendace for a Specific Period");
        specificPeriodBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specificPeriodBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(specificPeriodBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allRecordsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {allRecordsBtn, specificPeriodBtn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(specificPeriodBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(allRecordsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {allRecordsBtn, specificPeriodBtn});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void specificPeriodBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specificPeriodBtnActionPerformed
        new SelectDateRange(view,  employee,  attendanceController,  payrollController).setVisible(true);
    }//GEN-LAST:event_specificPeriodBtnActionPerformed

    private void allRecordsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allRecordsBtnActionPerformed
        view.displayAllAttendanceRecords(payrollSummaryAll);
    }//GEN-LAST:event_allRecordsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecordsChoices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecordsChoices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecordsChoices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecordsChoices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecordsChoices().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton allRecordsBtn;
    private javax.swing.JButton specificPeriodBtn;
    // End of variables declaration//GEN-END:variables
}
