package com.motorph.payroll;

import com.motorph.payroll.controller.AttendanceController;
import com.motorph.payroll.controller.EmployeeController;
import com.motorph.payroll.controller.PayrollController;
import com.motorph.payroll.dao.AttendanceDao;
import com.motorph.payroll.dao.DaoFactory;
import com.motorph.payroll.dao.EmployeeDao;
import com.motorph.payroll.service.AttendanceService;
import com.motorph.payroll.service.AttendanceServiceImpl;
import com.motorph.payroll.service.EmployeeService;
import com.motorph.payroll.service.EmployeeServiceImpl;
import com.motorph.payroll.service.PayrollService;
import com.motorph.payroll.service.PayrollServiceImpl;
import com.motorph.payroll.view.MainMenu;
import com.motorph.payroll.util.AppConstants;
import com.motorph.payroll.view.PayrollView;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;


/**
 *
 * @author Mark Montero, Lyca Mae Benipayo
 */
public class GUI extends javax.swing.JFrame {
    
    private MainMenu main;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUI.class.getName());

    /**
     * Creates new form GUI
     */
    // Real

    public GUI() {
        initComponents();
        this.getContentPane().setBackground(new java.awt.Color(204, 102, 255));
        
        // to make the window center on the screen.
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
        
        // Create DAOs
        EmployeeDao employeeDao = DaoFactory.createEmployeeDao();
        AttendanceDao attendanceDao = DaoFactory.createAttendanceDao();
        
        // Create Services
        EmployeeService employeeService = new EmployeeServiceImpl(employeeDao);
        AttendanceService attendanceService = new AttendanceServiceImpl(attendanceDao);
        PayrollService payrollService = new PayrollServiceImpl(attendanceDao);
        
        // Create Controllers
        EmployeeController employeeController = new EmployeeController(employeeService);
        AttendanceController attendanceController = new AttendanceController(attendanceService);
        PayrollController payrollController = new PayrollController(payrollService, employeeService);
        
        // Create View
        PayrollView view = new PayrollView();
        
        // Start the application
        MainMenu main = new MainMenu(view, employeeController, attendanceController, payrollController);
        this.main = main;
    }
 
    
    /*
    // Fake
    public static MainMenu createMainMenu() {
    // Create DAOs
    EmployeeDao employeeDao = DaoFactory.createEmployeeDao();
    AttendanceDao attendanceDao = DaoFactory.createAttendanceDao();

    // Create Services
    EmployeeService employeeService = new EmployeeServiceImpl(employeeDao);
    AttendanceService attendanceService = new AttendanceServiceImpl(attendanceDao);
    PayrollService payrollService = new PayrollServiceImpl(attendanceDao);

    // Create Controllers
    EmployeeController employeeController = new EmployeeController(employeeService);
    AttendanceController attendanceController = new AttendanceController(attendanceService);
    PayrollController payrollController = new PayrollController(payrollService, employeeService);

    // Create View
    PayrollView view = new PayrollView();

    // Return the MainMenu ready to show
    return new MainMenu(view, employeeController, attendanceController, payrollController)
            */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUser = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        txtLog1 = new javax.swing.JTextField();
        btnlblLogin = new javax.swing.JButton();
        lblTitle2 = new javax.swing.JLabel();
        lblTextLogin = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        lblLogo2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblBackground2 = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(587, 411));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUser.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblUser.setForeground(new java.awt.Color(51, 51, 51));
        lblUser.setText("Username");
        getContentPane().add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, -1, -1));

        lblPass.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblPass.setForeground(new java.awt.Color(51, 51, 51));
        lblPass.setText("Password");
        getContentPane().add(lblPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 70, -1));

        txtLog1.setBackground(new java.awt.Color(255, 255, 255));
        txtLog1.setForeground(new java.awt.Color(102, 102, 102));
        txtLog1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLog1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtLog1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 140, -1));

        btnlblLogin.setBackground(new java.awt.Color(153, 153, 153));
        btnlblLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnlblLogin.setText("Login");
        btnlblLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlblLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnlblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, -1, -1));

        lblTitle2.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 24)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(51, 51, 51));
        lblTitle2.setText("Employee App");
        getContentPane().add(lblTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        lblTextLogin.setFont(new java.awt.Font("FZYaoTi", 0, 18)); // NOI18N
        lblTextLogin.setForeground(new java.awt.Color(51, 51, 51));
        lblTextLogin.setText("Login to MotorPH");
        getContentPane().add(lblTextLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 160, 30));

        password.setBackground(new java.awt.Color(255, 255, 255));
        password.setForeground(new java.awt.Color(0, 0, 0));
        password.setToolTipText("");
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 140, -1));

        lblLogo2.setBackground(new java.awt.Color(0, 0, 0));
        lblLogo2.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 26)); // NOI18N
        lblLogo2.setForeground(new java.awt.Color(255, 255, 255));
        lblLogo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo2.setText("MotorPH");
        lblLogo2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblLogo2.setOpaque(true);
        getContentPane().add(lblLogo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 130, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logochoice170x170.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 170, 90));

        lblBackground2.setBackground(new java.awt.Color(255, 255, 255));
        lblBackground2.setForeground(new java.awt.Color(0, 0, 0));
        lblBackground2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblBackground2.setOpaque(true);
        getContentPane().add(lblBackground2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 220, 240));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gradient.png"))); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 580, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLog1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLog1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLog1ActionPerformed

    private void btnlblLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlblLoginActionPerformed
        if (txtLog1.getText().equals(AppConstants.ADMIN_USERNAME) && new String(password.getPassword()).equals(AppConstants.ADMIN_PASSWORD)) {
            JOptionPane.showMessageDialog(null, "Success");
            main.setVisible(true);
            this.dispose();
            
        } else {
            JOptionPane.showMessageDialog(null, "Invalid credentials.");
        }
    }//GEN-LAST:event_btnlblLoginActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed
    private void usernameActionPerformed(java.awt.event.ActionEvent evt) { 
    }                                        
        // TODO add your handling code here:
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true); // MS2 for Now
                // Set Aside GUI (with Login)
               //new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlblLogin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBackground2;
    private javax.swing.JLabel lblLogo2;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblTextLogin;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField txtLog1;
    // End of variables declaration//GEN-END:variables
}
